[project]
name = "intent-citation-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "seaborn>=0.13.2",
    "transformers>=4.53.2",
]
